### ISSUE TITLE
License? 

### ISSUE THREAD

**Issue by forki** [NewMotion/ocpp#14]
I can't find a license.txt. What license is this project?

**Comment by AnCh7** [comment]
Hi NewMotion team, can u please provide us information about the license?

**Comment by reinierl** [comment]
Well, I can provide you with a clarification of the situation as it is: NewMotion has the copyright on most of this code, and currently NewMotion is *not* giving a license to redistribute this code to anyone. That means that's while it's on public display here, until further notice, it's not really open source. 

We are working on making this library open source under a popular license.

**Comment by forki** [comment]
thanks

**Comment by reinierl** [comment]
The project is now licensed under the GPL.
