### ISSUE TITLE
SOAP example

### ISSUE THREAD

**Issue by monti-cistella** [NewMotion/ocpp#19]
Hi all,

I've been trying to create a SOAP server example for the central system without any success. Can anybody share some basic instructions for this?

Thanks in advance.

**Comment by reinierl** [comment]
Did you see [the OcppProcessing test](https://github.com/NewMotion/ocpp/blob/master/ocpp-spray/src/test/scala/com/thenewmotion/ocpp/spray/OcppProcessingSpec.scala) yet? I think that that is as much documentation as there is right now.
