### ISSUE TITLE
Incorrect README?

### ISSUE THREAD

**Issue by eduhenke** [NewMotion/ocpp#28]
I'm new to sbt/scala and also Java dependencies, in the README file it says to add to `build.sbt` the following line:
`libraryDependencies += "com.thenewmotion" %% "ocpp-j-api" % "9.0.1"`
though I could only make it work when I added the following line:
`libraryDependencies += "com.thenewmotion.ocpp" %% "ocpp-j-api" % "9.0.0"`

Am I or the README wrong?

**Comment by reinierl** [comment]
Ah, you're completely right! I'm sorry about missing your issue so far, I'll fix it right away.
