### ISSUE TITLE
Calling library from Java

### ISSUE THREAD

**Issue by emerout** [NewMotion/ocpp#33]
Hello, 
Is this ocpp library easily callable from Java code ?

**Comment by reinierl** [comment]
Generally speaking, no. It relies heavily on Scala-specific functionalities like traits, implicit parameters and `Future`s. 

Probably the easiest approach to calling this from Java would be to write a glue layer in Scala that exposes a Java-friendly interface. That would be interesting to see developed as a separate project or a pull request to this one.
